name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: SSH连接并部署
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

          ssh root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /root/item/SmartLink_Index

            # 拉最新代码
            git pull origin dev

            # ===== 后端 =====
            cd zhilian-backend
            mvn clean package -DskipTests

            pkill -f zhilian || true
            nohup java -jar target/zhilian-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &

            # ===== 前端 =====
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22

            cd ../zhilian-frontend
            npm install
            npm run build

            # 拷贝到 nginx 目录
            rm -rf /var/www/zhilian/*
            cp -r dist/* /var/www/zhilian/

            # 重启 nginx
            systemctl restart nginx

            echo "部署完成"
